# Generated by Django 5.1.5 on 2025-04-04 19:46

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0011_chatgroup_admin_chatgroup_groupchat_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='encrypted_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='users_online',
            field=models.ManyToManyField(blank=True, default=shortuuid.main.ShortUUID.uuid, related_name='online_in_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
